config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :inline_issues do
    collection do
      get :edit_multiple
    end
  end
end

resources :inline_issues do
  collection do
    get :edit_multiple
    put :update_multiple
  end
end


  

app/controllers/inline_issues_controller.rb
class InlineIssuesController < ApplicationController
  before_filter :find_project, :only => [:edit_multiple, :update_multiple]
  before_filter :retrieve_query, :get_ids_before_edit, :only => [:edit_multiple]
  before_filter :get_ids_before_update, :only => [:update_multiple]
  before_filter :find_projects, :authorize, :only => [:edit_multiple, :update_multiple]
  

  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper
  include IssuesHelper
  include InlineIssuesHelper

  def edit_multiple
    description_column = @query.columns.select{|c| c.name == :description}.first
    @query_inline_columns = description_column.present? ? 
      @query.inline_columns.insert(1, description_column) :
      @query.inline_columns

    sort_init(@query.sort_criteria.empty? ? [['id', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    @query.sort_criteria = sort_criteria.to_a

    if @query.valid? 
      @limit = per_page_option
      @issue_count = @query.issue_count
      @issue_pages = Paginator.new @issue_count, @limit, params['page']
      @offset ||= @issue_pages.offset
      @issues = @query.issues(:include => [:assigned_to, :tracker, :priority, :category, :fixed_version],
                              :order => sort_clause,
                              :offset => @offset,
                              :limit => @limit,
                              :conditions => inline_edit_condition)

      @ids = @issues.map(&:id)
                              
      @issue_count_by_group = issue_count_by_group
      
      @priorities = IssuePriority.active
    else
      # respond_to do |format|
        # format.html { render(:template => 'issues/index', :layout => !request.xhr?) }
        # format.any(:atom, :csv, :pdf) { render(:nothing => true) }
        # format.api { render_validation_errors(@query) }
      # end
    end
    @back_url = @project ? project_issues_path(@project) : params[:back_url]
    @update_url = @project ? update_multiple_inline_issues_path(:project_id => @project) : update_multiple_inline_issues_path(:ids => @ids)
  rescue ActiveRecord::RecordNotFound
    render_404
  rescue Query::StatementInvalid
    flash[:error] = l('label_no_issues_selected')
    redirect_to :back
  end

  def update_multiple
    errors = []
    Issue.find(params[:issues].keys).each do |i|
      upd = i.update_attributes(params[:issues][i.id.to_s])
      errors += i.errors.full_messages.map{|m| l(:label_issue)+" #{i.id}: "+m} if !upd
    end

    if errors.present?
      flash[:error] = errors.to_sentence
      redirect_to :back
    else
      flash[:notice] = l(:notice_successful_update)
      redirect_back_or_default params[:back_url] #_project_issues_path(@project)
    end
  end
  
  private
  
  def get_ids_before_edit
    @ids = []
    if params[:ids].present?
      if params[:ids].class.name == "Array"
        @ids = params[:ids]
      elsif params[:ids].class.name == "String"
        @ids = params[:ids].split(" ")
      end
    else
      @ids = @query.issues(:include => [:assigned_to, :tracker, :priority, :category, :fixed_version]).map(&:id)
    end
    @ids
  end

  def get_ids_before_update
    @ids = []
    if params[:ids].present?
      if params[:ids].class.name == "Array"
        @ids = params[:ids]
      elsif params[:ids].class.name == "String"
        @ids = params[:ids].split(" ")
      end
    end
    @ids
  end
  
  def find_project
    @project = Project.find(params[:project_id]) if params[:project_id].present?
    # @projects = params[:projects_id].present? ? Project.find(params[:projects_id]) : (params[:ids].present? ? Issue.find(params[:ids]).map(&:project_id).uniq : nil)
  end

  def find_projects
    @projects = @ids ? Issue.find(@ids).map(&:project).uniq : nil
  end
  
  # Returns the issue count by group or nil if query is not grouped
  def issue_count_by_group
    r = nil
    if @query.grouped?
      begin
        # Rails3 will raise an (unexpected) RecordNotFound if there's only a nil group value
        r = Issue.visible.
          joins(:status, :project).
          where(@query.statement).
          joins(joins_for_order_statement(@query.group_by_statement)).
          group(@query.group_by_statement).
          where(inline_edit_condition).
          count
      rescue ActiveRecord::RecordNotFound
        r = {nil => @query.issue_count}
      end
      c = @query.group_by_column
      if c.is_a?(QueryCustomFieldColumn)
        r = r.keys.inject({}) {|h, k| h[c.custom_field.cast_value(k)] = r[k]; h}
      end
    end
    r
  rescue ::ActiveRecord::StatementInvalid => e
    raise StatementInvalid.new(e.message)
  end
  
  # Additional joins required for the given sort options
  def joins_for_order_statement(order_options)
    joins = []

    if order_options
      if order_options.include?('authors')
        joins << "LEFT OUTER JOIN #{User.table_name} authors ON authors.id = #{queried_table_name}.author_id"
      end
      order_options.scan(/cf_\d+/).uniq.each do |name|
        column = available_columns.detect {|c| c.name.to_s == name}
        join = column && column.custom_field.join_for_order_statement
        if join
          joins << join
        end
      end
    end

    joins.any? ? joins.join(' ') : nil
  end
  
end

app/helpers/inline_issues_helper.rb
module InlineIssuesHelper
  include CustomFieldsHelper

  def inline_project_id
    @project.present? ? @project.id : ""
  end
  
  def column_form_content(column, issue, f)
    if(column.class.name == "QueryCustomFieldColumn")      
      custom_field_values = issue.editable_custom_field_values
      value = custom_field_values.detect{|cfv| cfv.custom_field_id == column.custom_field.id}
      custom_field_tag :issues, value, issue if value.present?
    else 
      case column.name
      when :tracker
        f.select :tracker_id, issue.project.trackers.collect {|t| [t.name, t.id]}
      when :status
        f.select :status_id, issue.new_statuses_allowed_to.collect {|p| [p.name, p.id]}
      when :priority
        f.select :priority_id, @priorities.collect {|p| [p.name, p.id]}
      when :subject
        f.text_field :subject, size: 20
      when :assigned_to
        f.select :assigned_to_id, principals_options_for_select(issue.assignable_users, issue.assigned_to), :include_blank => true
      when :estimated_hours
        f.text_field :estimated_hours, size: 3
      when :start_date
        f.text_field(:start_date, size: 8) +
        calendar_for('issues_'+issue.id.to_s+'_start_date') 
      when :due_date
        f.text_field(:due_date, size: 8) +
        calendar_for('issues_'+issue.id.to_s+'_due_date')
      when :done_ratio 
        f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] })
      when :is_private
        f.check_box :is_private
      when :description
        f.text_area :description
      when :category
        f.select :category_id, [["",""]] + issue.project.issue_categories.collect {|t| [t.name, t.id]}
      when :fixed_version
        f.select :fixed_version_id, [["",""]] + issue.project.versions.collect {|t| [t.name, t.id]}
      else
        column_display_text(column, issue)
      end    
    end
  end
  
  def column_display_text(column, issue)    
    value = column.value(issue)
    
    case value.class.name
    when 'Time'
      format_time(value)
    when 'Date'
      format_date(value)
    when 'Float'
      sprintf "%.2f", value
    when 'TrueClass'
      l(:general_text_Yes)
    when 'FalseClass'
      l(:general_text_No)
    else
      h(value)
    end
  end
  
  def column_total(column, issues)
    case column.name
    when :estimated_hours
      totalEstHours(issues)
    when :spent_hours
      totalSpentHours(issues)
    end    
  end
  
  def group_column_total(column, issues, group)
    case column.name
    when :estimated_hours
      totalGroupEstHours(issues, group)
    when :spent_hours
      totalGroupSpentHours(issues, group)
    end 
  end
  
  def inline_edit_condition
    cond = "issues.id in (#{@ids.map{|i| i.to_i}.join(',')})"
  end
  
  def group_class_name(group)
    begin
      if group.present?
        # strip out white spaces from the group name
        "group_" + group.name.gsub(/\s+/,"")
      else
        ""
      end
    rescue
      ""
    end
  end
  
  def group_total_name(group, column)
    if group.present? && column.present?
      "#{group_class_name(group)}_total_#{column.name}"
    else
      ""
    end
  end
  
  private
  
  def totalEstHours(issues)
    estTotal = 0
    issues.each {|i| estTotal += i.estimated_hours if i.estimated_hours.present?}
    sprintf "%.2f", estTotal
  end
  
  def totalSpentHours(issues)
    spentTotal = 0
    issues.each {|i| spentTotal += i.spent_hours if i.spent_hours.present?}
    sprintf "%.2f", spentTotal
  end
  
  def totalGroupEstHours(issues, group)
    estTotal = 0
    issues.each do |i| 
      if i.estimated_hours.present? &&  @query.group_by_column.value(i) == group
        estTotal += i.estimated_hours
      end
    end
    sprintf "%.2f", estTotal
  end
  
  def totalGroupSpentHours(issues, group)
    spentTotal = 0
    issues.each do |i| 
      if i.spent_hours.present? &&  @query.group_by_column.value(i) == group
        spentTotal += i.spent_hours 
      end
    end
    sprintf "%.2f", spentTotal
  end
  
  
  #####
  # Return custom field html tag corresponding to its format
  #####
  def custom_field_tag(name, custom_value, issue)
    custom_field = custom_value.custom_field
    field_name = "#{name}[#{issue.id}][custom_field_values][#{custom_field.id}]"
    field_name << "[]" if custom_field.multiple?
    field_id = "#{name}_custom_field_values_#{custom_field.id}"

    tag_options = {:id => field_id, :class => "#{custom_field.field_format}_cf"}

    field_format = Redmine::FieldFormat.find(custom_field.field_format)
    case custom_field.field_format
    when "date"
      text_field_tag(field_name, custom_value.value, tag_options.merge(:size => 10)) +
      calendar_for(field_id)
    when "text"
      text_area_tag(field_name, custom_value.value, tag_options.merge(:rows => 4, :cols => 65, :style => "width:auto; resize:both;"))
    when "bool"
      custom_value.custom_field.format.edit_tag self,
        field_id,
        field_name,
        custom_value,
        :class => "#{custom_value.custom_field.field_format}_cf"
    when "list"
    when "enumeration"
      blank_option = ''.html_safe
      unless custom_field.multiple?
        if custom_field.is_required?
          unless custom_field.default_value.present?
            blank_option = content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '')
          end
        else
          blank_option = content_tag('option')
        end
      end
      s = select_tag(field_name, blank_option + options_for_select(custom_field.possible_values_options(custom_value.customized), custom_value.value),
        tag_options.merge(:multiple => custom_field.multiple?))
      if custom_field.multiple?
        s << hidden_field_tag(field_name, '')
      end
      s
    else
      text_field_tag(field_name, custom_value.value, tag_options)
    end
  end
  
end

app/views/inline_issues/_context_menu_hook.html.erb
<% if !@issue and params[:back_url].present? %>
    <li>
    	<%
    	uri = URI.parse(params[:back_url])
    	if uri.query.present?
	    	args = CGI.parse(uri.query)
	    	col = args.keys.include?('c[]') ? args['c[]'] : nil
	    end
    	%>
        <%= context_menu_link l(:button_inline_edit), @project ? edit_multiple_project_inline_issues_path(@project, :ids => @issue_ids, :c => col) : edit_multiple_inline_issues_path(:ids => @issue_ids, :back_url => params[:back_url], :c => col), :class => 'icon-edit', :disabled => !@can[:edit] %>
        <%#= context_menu_link l(:button_inline_edit), '#', :onclick => "$('#query_form').attr('action', '"+(@project ? edit_multiple_project_inline_issues_path(@project, :ids => @issue_ids) : edit_multiple_inline_issues_path(:ids => @issue_ids, :back_url => params[:back_url]))+"').submit();", :class => 'icon-edit', :disabled => !@can[:edit] %>
    </li>
<% end %>

app/views/inline_issues/_edit_form.html.erb
<%= form_tag @update_url, :id => 'inline_edit_form', method: :put do %>
    <%= hidden_field_tag 'back_url', @back_url %>
    <div class="autoscroll">
        <table class="list issues">
            <thead>
                <% @query_inline_columns.each do |column| %>
                    <%= column_header(column) %>
                <% end %>
            </thead>
            <% previous_group = false %>
            <tbody>
                <% @issues.each do |issue| %>
                    <%= fields_for "issues[]", issue do |f| %>
                        <% if @query.grouped? && (group = @query.group_by_column.value(issue)) != previous_group %>
                            <% reset_cycle %>
                
                            <% if previous_group %>
                                <%= render 'group_totals', group: previous_group, query: @query%>
                            <% end %>
                
                            <tr class="group open">
                                <td colspan="<%= @query_inline_columns.size + 2 %>">
                                    <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span> 
                                    <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, issue) %> 
                                    <span class="count"><%= @issue_count_by_group[group] %></span> 
                                    <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %> 
                                </td>
                            </tr>
                            <% previous_group = group %>
                        <% end %>
                        <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> ">
                            <% @query_inline_columns.each do |column| %>
                                <td class="<%= column.css_classes %> <%= group_class_name(group) %>"> <%= column_form_content(column, issue, f) %> </td>
                            <% end %>
                        </tr>
                    <% end %>
                <% end %>
                <% if previous_group %>
                    <%= render 'group_totals', group: previous_group, query: @query%>
                <% end %>
                <tr class="inline_totals">
                    <% @query_inline_columns.each do |column| %>
                        <td id="total-<%= column.name %>"><%= column_total(column, @issues)%></td>
                    <% end %>
                </tr>
            </tbody>
        </table>
    </div>
    <%= submit_tag l(:button_submit) %>
    <input name="resetform" type="reset" id="inline_edit_reset" value="Reset" />
    <%= link_to l(:button_cancel), @back_url %>
<% end %>

app/views/inline_issues/_group_totals.html.erb
<tr class="group inline_group_totals">
    <% query.inline_columns.each do |column| %>
        <td id=<%= group_total_name(group, column) %>><%= group_column_total(column, @issues, group)%></td>
    <% end %>
</tr>

app/views/inline_issues/_options_form.html.erb
<%= form_tag({ :controller => 'inline_issues', :action => 'edit_multiple', :project_id => @project, :ids => @ids },
            :method => :get, :id => 'query_form') do %>
    <%= hidden_field_tag 'set_filter', '1' %>
    <%= hidden_field_tag 'ids', @ids %>
    <%= hidden_field_tag 'project_id', @project.id %>
    <div id="query_form_content" class="hide-when-print">
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>
          <tr>
            <td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons hide-when-print">

    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project, :ids => @ids }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }'); submit_query_form('query_form')",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>
<% end %>

app/views/inline_issues/edit_multiple.html.erb
<h2><%= l(:label_inline_edit_selected_issues) %></h2>

<%#= render 'options_form'%>

<%= render 'edit_form'%>


<div id="field_original">
    <div id="field_original_value">#</div>
</div>


<% content_for :header_tags do %>
  <%= stylesheet_link_tag "inline_edit_issues", :plugin => 'redmine_inline_edit_issues' %>
  <%= javascript_include_tag "inline_edit_issues", :plugin => 'redmine_inline_edit_issues' %>
<% end %>